import "./button.css";
import "./style.css";
import "./Form.css";
import "./DropdownStylized.css";
import "./Table.css";
import "./LoginPage.css";
import "./ProfileStyle.css";
import "./FaceEntry.css";
import "./modal.css";
